In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
scalar = 3.7
arr = np.array([6, 7, 8, 9, 5, 4])

sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)


exp_values = np.exp(arr)
log_values = np.log(arr)

abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

rem_values = np.remainder(arr, 2)

round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.2794155   0.6569866   0.98935825  0.41211849 -0.95892427 -0.7568025 ]
cos: [ 0.96017029  0.75390225 -0.14550003 -0.91113026  0.28366219 -0.65364362]
tan: [-0.29100619  0.87144798 -6.79971146 -0.45231566 -3.38051501  1.15782128]
asin: [0.72972766 0.89112251 1.09491408 1.57079633 0.58903097 0.46055399]
acos: [0.84106867 0.67967382 0.47588225 0.         0.98176536 1.11024234]
atan: [1.40564765 1.42889927 1.44644133 1.46013911 1.37340077 1.32581766]
exp: [ 403.42879349 1096.63315843 2980.95798704 8103.08392758  148.4131591
   54.59815003]
log: [1.79175947 1.94591015 2.07944154 2.19722458 1.60943791 1.38629436]
abs: [6 7 8 9 5 4]
sqrt: [2.44948974 2.64575131 2.82842712 3.         2.23606798 2.        ]
rem: [0 1 0 1 1 0]
round: [6 7 8 9 5 4]
floor: [6. 7. 8. 9. 5. 4.]
ceil: [6. 7. 8. 9. 5. 4.]


In [ ]:
matrix = np.array([[1.5, 2], [-3, 4.5], [-5.6, -6]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)


exp_values = np.exp(matrix)
log_values = np.log(matrix)


abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[ 1.5  2. ]
 [-3.   4.5]
 [-5.6 -6. ]]

sin:
 [[ 0.99749499  0.90929743]
 [-0.14112001 -0.97753012]
 [ 0.63126664  0.2794155 ]]

cos:
 [[ 0.0707372  -0.41614684]
 [-0.9899925  -0.2107958 ]
 [ 0.77556588  0.96017029]]

tan:
 [[14.10141995 -2.18503986]
 [ 0.14254654  4.63733205]
 [ 0.81394328  0.29100619]]

asine:
 [[ 0.33983691  0.46055399]
 [-0.72972766  1.57079633]
 [-1.57079633 -1.57079633]]

acosine:
 [[1.23095942 1.11024234]
 [2.30052398 0.        ]
 [3.14159265 3.14159265]]

atangent:
 [[ 0.98279372  1.10714872]
 [-1.24904577  1.35212738]
 [-1.39408747 -1.40564765]]

exp:
 [[4.48168907e+00 7.38905610e+00]
 [4.97870684e-02 9.00171313e+01]
 [3.69786372e-03 2.47875218e-03]]

log (natural):
 [[0.40546511 0.69314718]
 [       nan 1.5040774 ]
 [       nan        nan]]

abs:
 [[1.5 2. ]
 [3.  4.5]
 [5.6 6. ]]

sqrt:
 [[1.22474487 1.41421356]
 [       nan 2.12132034]
 [       nan        nan]]

rem (remainder when divided by 2):
 [[1.5 0. ]
 [1.  0.5]
 [0.4 0. ]]

round:
 [[ 2.  

/tmp/ipython-input-2000977977.py:14: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)  # Natural logarithm (log base e)
/tmp/ipython-input-2000977977.py:18: RuntimeWarning: invalid value encountered in sqrt
  sqrt_values = np.sqrt(matrix)


In [ ]:
# Sample vector (1D array)
vec = np.array([3.4, 1.2, 4.5, -1.6, 5, 9, 2, 6])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)

Max value: 9.0 at index 5
Min value: -1.6 at index 3
Length of vector: 8
Sorted vector: [-1.6  1.2  2.   3.4  4.5  5.   6.   9. ]
Sum of elements: 29.5
Product of elements: -15863.04
Median value: 3.95
Mean value: 3.6875
Standard deviation: 3.021356276575141


In [6]:
#Perform 2×3 Matrix with float values

vec = np.array([[5.6, 4.6, 3.5], [5.2, 4.7, 8.9]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 8.9 at index 5
Min value: 3.5 at index 2
Length of vector: 2
Sorted vector: [[3.5 4.6 5.6]
 [4.7 5.2 8.9]]
Sum of elements: 32.5
Product of elements: 19611.242560000002
Median value: 4.95
Mean value: 5.416666666666667
Standard deviation: 1.6866304343934455
